allow_remote_control yes
# Other unix systems:
listen_on unix:/tmp/mykitty

# general keymap
macos_option_as_alt                          yes

# vim keymap
map cmd+s send_text all                      \e:w\r

# ############### keymap undo ####################
# 取消打开新标签页   no_op =  无操作，即禁止该快捷键操作
# 取消快捷键
map ctrl+shift+h                             no_op
map ctrl+shift+j                             no_op
map ctrl+shift+k                             no_op
map ctrl+shift+l                             no_op
# command+t 可以打开新标签页
map ctrl+shift+t                             no_op 
# command+enter 可进行分屏
# map ctrl+shift+enter                         no_op
# ctrl+shift+.可以重启
# ctrl+shift+f5 已恢复默认（reload config）
map ctrl+shift+r                             no_op


# ############### keymap config ####################
# 横分屏（上下）
map cmd+enter                                launch --bias=50 --location=hsplit --cwd=current
# 竖分屏（左右）
# map ctrl+shift+enter                         launch --bias=50 --location=vsplit --cwd=current
# 分屏窗口移动
map cmd+j kitten pass_keys.py neighboring_window bottom cmd+j
map cmd+k kitten pass_keys.py neighboring_window top    cmd+k
map cmd+h kitten pass_keys.py neighboring_window left   cmd+h
map cmd+l kitten pass_keys.py neighboring_window right  cmd+l

# 关闭当前分屏窗口
# map cmd+x                                    close_window
